import type { NextPage } from 'next'
import Container from 'app/components/Container'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Container id="dashboard-page" className="py-4 md:py-8 lg:py-12" maxWidth="2xl">
        <Head>
          <title>Dashboard | Next </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Container>

    </div>
  )
}

export default Home
